### ISSUE TITLE
Authentification errors can't be handled properly

### ISSUE THREAD

**Issue by karlem** [pusher/pusher-platform-nodejs#12]
### What?
Authentification errors can't be handled properly since authenticate on function on Authenticator class works just with Node.js http request object:

https://github.com/pusher/pusher-platform-nodejs/blob/44a5786488618d150490103c6c87325184d75866/src/authenticator.ts#L17

It means that I can't handle my custom error in my app using this SDK since SDK sending error to client straight by http response without letting the user know about error. In practise that could mean that user of SDK is not able to log that event in the way he wish to.

### Suggested improvements

I would export generateToken method on App class so user can decide whether he wants to use this authenticate method or generate token synchronously and then handle error manually.

Similar to: https://github.com/pusher/pusher-http-node/blob/master/lib/pusher.js#L104 but with proper error handling.
 
---- 

CC @pusher/sigsdk

**Comment by zmarkan** [comment]
I think it make sense

**Comment by pl** [comment]
Hm, there are two parts to this issue - one isn't really a problem, I think. 

The `authenticate` method is only meant to handle the happy case when the server identified the user and decided to provide the user with an access token. Any errors should be raised before calling it, so there's nothing that stops the server from logging and sending an error response.

However, we're not really hiding the response format well, because error responses must be formatted in a specific way. I'd be happy to split out the token generation method and maybe expand this request-response API to handle errors too.
